### ISSUE TITLE
Theme displaying incorrectly in RustRover

### ISSUE THREAD

**Issue by Swarkin** [jasonhulbert/jetbrains-trash-panda-theme#48] opened 2023-12-30 18:12 UTC
RustRover:
![explorer_Tpa30Bmhai](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/102416174/60f530a8-ca7b-4375-ba85-78072dfd6a0c)

PyCharm:
![explorer_To2zXfBLAF](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/102416174/746c06de-5721-4c28-8ae0-8f9a3c756d30)

**Comment by jasonhulbert** [comment] 2024-01-02 15:07
@Swarkin Are you getting any IDE errors? What version of RustRover are you on?

**Comment by Swarkin** [comment] 2024-01-02 15:34
Im using the latest version: `RustRover 2023.3 EAP Build #RR-233.11799.306`
No errors are popping up, is there some log file I would have to check? All default themes are working fine, I tried another plugin theme called `Dark Purple Theme` and it applied correctly.

**Comment by jasonhulbert** [comment] 2024-01-02 15:47
There were several other issues encountered in recent updates in various products. Ultimately it seemed to be caused by the corresponding "color scheme" associated with an ide ui "theme" was not being applied correctly. The issue that I reported on YouTrack is closed now and it appears to have been addressed in intellij, webstorm, pycharm and rider. Perhaps there's still a patch that will be pushed out for RustRover? I'll leave this open for now.

https://github.com/jasonhulbert/jetbrains-trash-panda-theme/issues/44#issuecomment-1861231617

**Comment by rlycluster** [comment] 2024-01-09 06:32
![Screenshot 2024-01-09 152001](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/83150885/99d00cbd-c16a-4a49-8940-e383dd589a44)
Uhm so hi. Other themes (high contrast, moonlight, light) as well as other plugins work fine. But this one (default) it seems to me shouldn't look like this
Version: CLion 2023.3.2 CL-233.13135.93

**Comment by jasonhulbert** [comment] 2024-01-09 17:20
@mpdesign-dev @rlycluster Does manually changing to the correct, corresponding color scheme work? https://github.com/jasonhulbert/jetbrains-trash-panda-theme/issues/50#issuecomment-1875409526

I'm not sure why some IDEs do this but it appears that sometimes when switching appearance -> theme, the corresponding coor scheme is not automatically applied as well.

**Comment by rlycluster** [comment] 2024-01-09 17:34
@jasonhulbert, it works! Thanks😀

**Closed** 2024-01-10 13:50 UTC

**Comment by Swarkin** [comment] 2024-01-10 18:37
It works for me now since the latest RustRover update
