### ISSUE TITLE
<Question> how to change selection color and button color?

### ISSUE THREAD

**Issue by Ceilzcx** [jasonhulbert/jetbrains-trash-panda-theme#31] opened 2023-06-15 03:04 UTC
hi, I use your theme plugin in idea, it is great. I think the color of the button is too dark, I don't know how to adjust the color. can you please tell me? thank you
i want to change the selection color and the border of button, use a softer blue
![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/48920254/d6c96eda-bb6d-4091-a7d1-5695d2ef2385)

**Comment by Ceilzcx** [comment] 2023-06-15 03:35
is this a bug? or setting something else，when mouse hover，ui has some problems
![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/48920254/734db99a-dd17-40e3-af99-566378b02dbd)

**Comment by jasonhulbert** [comment] 2023-12-18 18:18
Question regarding button color can be found in jetbrains documentation.

Question regarding rendering issues of radio buttons is duplicate of https://github.com/jasonhulbert/jetbrains-trash-panda-theme/issues/28

**Closed by jasonhulbert** 2023-12-18 18:18 UTC
